name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 10
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: |
        dotnet restore src\Sigurn.Rpc.Generator\Sigurn.Rpc.Generator.csproj
        dotnet restore src\Sigurn.Rpc\Sigurn.Rpc.csproj
        dotnet restore src\Sigurn.Rpc.Tests\Sigurn.Rpc.Tests.csproj
    - name: Build Debug
      run: |
        dotnet build --no-restore src\Sigurn.Rpc.Generator\Sigurn.Rpc.Generator.csproj
        dotnet build --no-restore src\Sigurn.Rpc\Sigurn.Rpc.csproj
        dotnet build --no-restore src\Sigurn.Rpc.Tests\Sigurn.Rpc.Tests.csproj
    - name: Build Release
      run: |
        dotnet build --no-restore -c Release src\Sigurn.Rpc.Generator\Sigurn.Rpc.Generator.csproj 
        dotnet build --no-restore -c Release src\Sigurn.Rpc\Sigurn.Rpc.csproj
        dotnet build --no-restore -c Release src\Sigurn.Rpc.Tests\Sigurn.Rpc.Tests.csproj
    - name: Test Debug
      run: dotnet test --no-build --verbosity normal src\Sigurn.Rpc.Tests\Sigurn.Rpc.Tests.csproj
    - name: Test Release
      run: dotnet test --no-build --verbosity normal -c Release src\Sigurn.Rpc.Tests\Sigurn.Rpc.Tests.csproj
    - name: Restore Integration Tests
      run: dotnet restore --verbosity normal src\Sigurn.Rpc.IntegrationTests\Sigurn.Rpc.IntegrationTests.csproj
    - name: Build Debug Integration Tests
      run: dotnet build --no-restore src\Sigurn.Rpc.IntegrationTests\Sigurn.Rpc.IntegrationTests.csproj
    - name: Build Release Integration Tests
      run: dotnet build --no-restore -c Release src\Sigurn.Rpc.IntegrationTests\Sigurn.Rpc.IntegrationTests.csproj
    - name: Integration Test Debug
      run: dotnet test --no-build --verbosity normal src\Sigurn.Rpc.IntegrationTests\Sigurn.Rpc.IntegrationTests.csproj
    - name: Integration Test Release 
      run: dotnet test --no-build --verbosity normal -c Release src\Sigurn.Rpc.IntegrationTests\Sigurn.Rpc.IntegrationTests.csproj
